### PR TITLE
License addition

### PR DESCRIPTION
**Pull request by jl-dos**
Proposing a license addition with a permissive MIT license or really any of your choosing. Many organizations require a license file to be present in a repo to consider it available for use.

### CODE REVIEW

**Comment by ejcx** [comment]
Any progress or comment here?

**Comment by mandatoryprogrammer** [comment]
Oops, totally didn't see this pull request. MIT sounds free enough for what I originally intended with open sourcing it :). If anyone has problems with this license please let me know.

**Comment by mandatoryprogrammer** [comment]
Also my apologies for not having this in the beginning, didn't even think about people not being able to use this for this reason.

**Comment by ejcx** [comment]
No problem. Thanks

**Pull request merged**
